name: CI
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2.4.0
      - uses: gradle/wrapper-validation-action@v1.0.4
      - uses: actions/setup-java@v2.3.1
        with:
          distribution: 'adopt-openj9'
          java-version: 11
      - uses: actions/cache@v2.1.7
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
  unit-tests:
    name: Unit tests
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2.4.0
      - uses: gradle/wrapper-validation-action@v1.0.4
      - uses: actions/setup-java@v2.3.1
        with:
          distribution: 'adopt-openj9'
          java-version: 11
      - uses: actions/cache@v2.1.7
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Unit tests
        run: ./gradlew testDebugUnitTest